# -*- coding: utf-8 -*-
"""Lip_SYNC_TASK

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HmyjmrMvKm5L3wRYxdr7ZOnB6P61f483
"""

import cv2
import moviepy.editor as mp

# Load the video and audio files
video_path = 'video.mp4' #path of your video file
audio_path = 'output10.wav' #path of your audio file

# Read the video frames
video = cv2.VideoCapture(video_path)
fps = video.get(cv2.CAP_PROP_FPS)
frame_width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

frame_count = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
video_duration = frame_count / fps

# Read the audio file
audio = mp.AudioFileClip(audio_path)
audio_duration = audio.duration

# Extract the video frames from the beginning to match the audio duration
video = mp.VideoFileClip(video_path).subclip(0, audio_duration)

# Set the audio of the video to the extracted audio
video = video.set_audio(audio)

# Set the video frames with the new audio
video_with_audio = video.set_fps(fps)

# Save the lip-synced video
output_path = 'output_video_1.mp4' # final ouput video name
video_with_audio.write_videofile(output_path, codec='libx264')